In [1]:
# importing libraries    
import numpy as nm    
import matplotlib.pyplot as mtp    
import pandas as pd   
from sklearn.cluster import DBSCAN
from numpy import unique
from numpy import where
from matplotlib import pyplot

In [2]:
# Importing the dataset  
dataset = pd.read_csv('data.csv')   
dataset.drop(dataset.index[dataset['game'] == 'Alternating'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Sustained'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Selective'], inplace = True)
dataset.drop(dataset.index[dataset['game'] == 'Divided'], inplace = True)

dataset.drop(dataset.index[dataset['child_age'] == 6], inplace = True)
dataset.drop(dataset.index[dataset['child_age'] == 7], inplace = True)

display(dataset)

,id,child_gender,child_age,total_correct_responses,correct_responses,commission_errors,omission_errors,mean_reaction_time,total_duration,diagnosis,percentage_no_of_correct_responses,oer,cer,game
79,80,1,4,10,10,0,0,1448,74000,No,100.000000,0.000000,0.0,Focused
80,81,1,4,10,10,0,0,1331,78000,No,100.000000,0.000000,0.0,Focused
81,82,1,4,10,10,0,0,1426,74500,No,100.000000,0.000000,0.0,Focused
82,83,2,4,10,10,0,0,1632,76000,No,100.000000,0.000000,0.0,Focused
83,84,2,4,10,9,0,1,1340,72000,No,90.000000,10.000000,0.0,Focused
84,85,2,4,10,10,0,0,1564,76000,No,100.000000,0.000000,0.0,Focused
85,86,2,4,10,8,0,2,1366,76000,No,80.000000,20.000000,0.0,Focused
86,87,2,4,10,10,0,0,1291,74500,No,100.000000,0.000000,0.0,Focused
87,88,2,4,10,8,0,2,2032,71500,No,80.000000,20.000000,0.0,Focused
88,89,2,4,10,9,0,1,1789,74000,No,90.000000,10.000000,0.0,Focused
89,90,2,4,10,10,0,0,1680,73500,No,100.000000,0.000000,0.0,Focused
90,91,1,4,10,9,0,1,1317,67500,No,90.000000,10.000000,0.0,Focused
91,92,1,4,10,10,0,0,1040,70500,No,100.000000,0.000000,0.0,Focused
92,93,1,4,10,10,0,0,1142,75500,No,100.000000,0.000000,0.0,Focused
93,94,1,4,10,10,0,0,1168,75000,No,100.000000,0.000000,0.0,Focused
94,95,1,4,10,10,0,0,1150,77000,No,100.000000,0.000000,0.0,Focused
95,96,1,4,10,10,0,0,1270,76000,No,100.000000,0.000000,0.0,Focused
96,97,1,4,10,9,0,1,1457,73000,No,90.000000,10.000000,0.0,Focused
97,98,1,4,10,10,0,0,1180,72500,No,100.000000,0.000000,0.0,Focused
98,99,1,4,10,9,0,1,1261,73500,No,90.000000,10.000000,0.0,Focused
99,100,1,4,10,7,0,3,1234,71500,No,70.000000,30.000000,0.0,Focused
100,101,1,4,10,10,0,0,1165,73000,No,100.000000,0.000000,0.0,Focused
101,102,1,4,10,10,0,0,1238,71000,No,100.000000,0.000000,0.0,Focused
102,103,1,4,10,9,0,1,1830,71000,No,90.000000,10.000000,0.0,Focused
103,104,1,4,10,8,0,2,1657,78000,No,80.000000,20.000000,0.0,Focused
104,105,1,4,10,7,0,3,1817,74000,No,70.000000,30.000000,0.0,Focused
105,106,2,5,12,11,0,1,1600,84500,No,91.666667,8.333333,0.0,Focused
106,107,2,5,12,11,0,1,1396,86500,No,91.666667,8.333333,0.0,Focused
107,108,2,5,12,12,0,0,1380,89000,No,100.000000,0.000000,0.0,Focused
108,109,2,5,12,12,0,0,1350,90000,No,100.000000,0.000000,0.0,Focused
109,110,2,5,12,12,0,0,1310,87000,No,100.000000,0.000000,0.0,Focused
110,111,2,5,12,12,0,0,1462,94000,No,100.000000,0.000000,0.0,Focused
111,112,1,5,12,12,0,0,1069,89000,No,100.000000,0.000000,0.0,Focused
112,113,1,5,12,12,0,0,1221,92000,No,100.000000,0.000000,0.0,Focused
113,114,1,5,12,10,0,2,1775,90000,No,83.333333,16.666667,0.0,Focused
114,115,2,5,12,10,0,2,1852,89500,No,83.333333,16.666667,0.0,Focused
115,116,2,5,12,11,0,1,1598,92000,No,91.666667,8.333333,0.0,Focused
116,117,2,5,12,12,0,0,1785,86000,No,100.000000,0.000000,0.0,Focused
117,118,2,5,12,12,0,0,1628,92000,No,100.000000,0.000000,0.0,Focused
118,119,2,5,12,12,0,0,1758,86500,No,100.000000,0.000000,0.0,Focused
119,120,2,5,12,12,0,0,1215,92000,No,100.000000,0.000000,0.0,Focused
120,121,2,5,12,12,0,0,1134,89000,No,100.000000,0.000000,0.0,Focused
121,122,2,5,12,11,0,1,1364,89000,No,91.666667,8.333333,0.0,Focused
122,123,2,5,12,12,0,0,1499,89000,No,100.000000,0.000000,0.0,Focused
123,124,2,5,12,12,0,0,1998,88000,No,100.000000,0.000000,0.0,Focused
124,125,2,5,12,10,0,2,1916,85500,No,83.333333,16.666667,0.0,Focused
125,126,2,5,12,12,0,0,1152,89500,No,100.000000,0.000000,0.0,Focused
126,127,2,5,12,12,0,0,1086,92500,No,100.000000,0.000000,0.0,Focused
127,128,2,5,12,12,0,0,1207,86500,No,100.000000,0.000000,0.0,Focused
128,129,2,5,12,12,0,0,1047,92000,No,100.000000,0.000000,0.0,Focused
129,130,2,5,12,10,0,2,1162,88500,No,83.333333,16.666667,0.0,Focused
130,131,2,5,12,12,0,0,1278,89000,No,100.000000,0.000000,0.0,Focused

In [3]:
# extracting only 11-comission & 12-omission
x = dataset.iloc[:, [7, 10, 11]].values  
display(x)

array([[1448.        ,  100.        ,    0.        ],
       [1331.        ,  100.        ,    0.        ],
       [1426.        ,  100.        ,    0.        ],
       [1632.        ,  100.        ,    0.        ],
       [1340.        ,   90.        ,   10.        ],
       [1564.        ,  100.        ,    0.        ],
       [1366.        ,   80.        ,   20.        ],
       [1291.        ,  100.        ,    0.        ],
       [2032.        ,   80.        ,   20.        ],
       [1789.        ,   90.        ,   10.        ],
       [1680.        ,  100.        ,    0.        ],
       [1317.        ,   90.        ,   10.        ],
       [1040.        ,  100.        ,    0.        ],
       [1142.        ,  100.        ,    0.        ],
       [1168.        ,  100.        ,    0.        ],
       [1150.        ,  100.        ,    0.        ],
       [1270.        ,  100.        ,    0.        ],
       [1457.        ,   90.        ,   10.        ],
       [1180.        ,  100.        ,    0.        ],
       [1261.        ,   90.        ,   10.        ],
       [1234.        ,   70.        ,   30.        ],
       [1165.        ,  100.        ,    0.        ],
       [1238.        ,  100.        ,    0.        ],
       [1830.        ,   90.        ,   10.        ],
       [1657.        ,   80.        ,   20.        ],
       [1817.        ,   70.        ,   30.        ],
       [1600.        ,   91.66666667,    8.33333333],
       [1396.        ,   91.66666667,    8.33333333],
       [1380.        ,  100.        ,    0.        ],
       [1350.        ,  100.        ,    0.        ],
       [1310.        ,  100.        ,    0.        ],
       [1462.        ,  100.        ,    0.        ],
       [1069.        ,  100.        ,    0.        ],
       [1221.        ,  100.        ,    0.        ],
       [1775.        ,   83.33333333,   16.66666667],
       [1852.        ,   83.33333333,   16.66666667],
       [1598.        ,   91.66666667,    8.33333333],
       [1785.        ,  100.        ,    0.        ],
       [1628.        ,  100.        ,    0.        ],
       [1758.        ,  100.        ,    0.        ],
       [1215.        ,  100.        ,    0.        ],
       [1134.        ,  100.        ,    0.        ],
       [1364.        ,   91.66666667,    8.33333333],
       [1499.        ,  100.        ,    0.        ],
       [1998.        ,  100.        ,    0.        ],
       [1916.        ,   83.33333333,   16.66666667],
       [1152.        ,  100.        ,    0.        ],
       [1086.        ,  100.        ,    0.        ],
       [1207.        ,  100.        ,    0.        ],
       [1047.        ,  100.        ,    0.        ],
       [1162.        ,   83.33333333,   16.66666667],
       [1278.        ,  100.        ,    0.        ]])

In [4]:
# standardizing the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
new_df = scaler.fit_transform(x)

# statistics of scaled data
pd.DataFrame(new_df).describe()

display(new_df)

array([[ 0.08876077,  0.65810029, -0.65810029],
       [-0.35063754,  0.65810029, -0.65810029],
       [ 0.00613887,  0.65810029, -0.65810029],
       [ 0.77978033,  0.65810029, -0.65810029],
       [-0.31683767, -0.56408597,  0.56408597],
       [ 0.52440354,  0.65810029, -0.65810029],
       [-0.2191936 , -1.78627223,  1.78627223],
       [-0.50085918,  0.65810029, -0.65810029],
       [ 2.28199678, -1.78627223,  1.78627223],
       [ 1.36940029, -0.56408597,  0.56408597],
       [ 0.96004631,  0.65810029, -0.65810029],
       [-0.40321512, -0.56408597,  0.56408597],
       [-1.4435    ,  0.65810029, -0.65810029],
       [-1.06043481,  0.65810029, -0.65810029],
       [-0.96279074,  0.65810029, -0.65810029],
       [-1.03039048,  0.65810029, -0.65810029],
       [-0.57972555,  0.65810029, -0.65810029],
       [ 0.12256064, -0.56408597,  0.56408597],
       [-0.91772425,  0.65810029, -0.65810029],
       [-0.61352542, -0.56408597,  0.56408597],
       [-0.71492503, -3.00845849,  3.00845849],
       [-0.97405736,  0.65810029, -0.65810029],
       [-0.69990286,  0.65810029, -0.65810029],
       [ 1.52337747, -0.56408597,  0.56408597],
       [ 0.87366886, -1.78627223,  1.78627223],
       [ 1.47455544, -3.00845849,  3.00845849],
       [ 0.65960302, -0.36038826,  0.36038826],
       [-0.10652737, -0.36038826,  0.36038826],
       [-0.16661603,  0.65810029, -0.65810029],
       [-0.27928226,  0.65810029, -0.65810029],
       [-0.4295039 ,  0.65810029, -0.65810029],
       [ 0.14133835,  0.65810029, -0.65810029],
       [-1.33458931,  0.65810029, -0.65810029],
       [-0.76374706,  0.65810029, -0.65810029],
       [ 1.31682271, -1.37887681,  1.37887681],
       [ 1.60599938, -1.37887681,  1.37887681],
       [ 0.65209194, -0.36038826,  0.36038826],
       [ 1.35437812,  0.65810029, -0.65810029],
       [ 0.76475817,  0.65810029, -0.65810029],
       [ 1.25297851,  0.65810029, -0.65810029],
       [-0.78628031,  0.65810029, -0.65810029],
       [-1.09047914,  0.65810029, -0.65810029],
       [-0.22670468, -0.36038826,  0.36038826],
       [ 0.28029337,  0.65810029, -0.65810029],
       [ 2.15430838,  0.65810029, -0.65810029],
       [ 1.84635401, -1.37887681,  1.37887681],
       [-1.0228794 ,  0.65810029, -0.65810029],
       [-1.27074511,  0.65810029, -0.65810029],
       [-0.81632464,  0.65810029, -0.65810029],
       [-1.41721122,  0.65810029, -0.65810029],
       [-0.98532399, -1.37887681,  1.37887681],
       [-0.54968122,  0.65810029, -0.65810029]])

In [5]:
x = dataset.iloc[:, [2, 7, 10, 11]].copy()
x[['mean_reaction_time', 'percentage_no_of_correct_responses', 'oer']] = new_df
x.head()
x = x.to_numpy()
display(x)

array([[ 4.        ,  0.08876077,  0.65810029, -0.65810029],
       [ 4.        , -0.35063754,  0.65810029, -0.65810029],
       [ 4.        ,  0.00613887,  0.65810029, -0.65810029],
       [ 4.        ,  0.77978033,  0.65810029, -0.65810029],
       [ 4.        , -0.31683767, -0.56408597,  0.56408597],
       [ 4.        ,  0.52440354,  0.65810029, -0.65810029],
       [ 4.        , -0.2191936 , -1.78627223,  1.78627223],
       [ 4.        , -0.50085918,  0.65810029, -0.65810029],
       [ 4.        ,  2.28199678, -1.78627223,  1.78627223],
       [ 4.        ,  1.36940029, -0.56408597,  0.56408597],
       [ 4.        ,  0.96004631,  0.65810029, -0.65810029],
       [ 4.        , -0.40321512, -0.56408597,  0.56408597],
       [ 4.        , -1.4435    ,  0.65810029, -0.65810029],
       [ 4.        , -1.06043481,  0.65810029, -0.65810029],
       [ 4.        , -0.96279074,  0.65810029, -0.65810029],
       [ 4.        , -1.03039048,  0.65810029, -0.65810029],
       [ 4.        , -0.57972555,  0.65810029, -0.65810029],
       [ 4.        ,  0.12256064, -0.56408597,  0.56408597],
       [ 4.        , -0.91772425,  0.65810029, -0.65810029],
       [ 4.        , -0.61352542, -0.56408597,  0.56408597],
       [ 4.        , -0.71492503, -3.00845849,  3.00845849],
       [ 4.        , -0.97405736,  0.65810029, -0.65810029],
       [ 4.        , -0.69990286,  0.65810029, -0.65810029],
       [ 4.        ,  1.52337747, -0.56408597,  0.56408597],
       [ 4.        ,  0.87366886, -1.78627223,  1.78627223],
       [ 4.        ,  1.47455544, -3.00845849,  3.00845849],
       [ 5.        ,  0.65960302, -0.36038826,  0.36038826],
       [ 5.        , -0.10652737, -0.36038826,  0.36038826],
       [ 5.        , -0.16661603,  0.65810029, -0.65810029],
       [ 5.        , -0.27928226,  0.65810029, -0.65810029],
       [ 5.        , -0.4295039 ,  0.65810029, -0.65810029],
       [ 5.        ,  0.14133835,  0.65810029, -0.65810029],
       [ 5.        , -1.33458931,  0.65810029, -0.65810029],
       [ 5.        , -0.76374706,  0.65810029, -0.65810029],
       [ 5.        ,  1.31682271, -1.37887681,  1.37887681],
       [ 5.        ,  1.60599938, -1.37887681,  1.37887681],
       [ 5.        ,  0.65209194, -0.36038826,  0.36038826],
       [ 5.        ,  1.35437812,  0.65810029, -0.65810029],
       [ 5.        ,  0.76475817,  0.65810029, -0.65810029],
       [ 5.        ,  1.25297851,  0.65810029, -0.65810029],
       [ 5.        , -0.78628031,  0.65810029, -0.65810029],
       [ 5.        , -1.09047914,  0.65810029, -0.65810029],
       [ 5.        , -0.22670468, -0.36038826,  0.36038826],
       [ 5.        ,  0.28029337,  0.65810029, -0.65810029],
       [ 5.        ,  2.15430838,  0.65810029, -0.65810029],
       [ 5.        ,  1.84635401, -1.37887681,  1.37887681],
       [ 5.        , -1.0228794 ,  0.65810029, -0.65810029],
       [ 5.        , -1.27074511,  0.65810029, -0.65810029],
       [ 5.        , -0.81632464,  0.65810029, -0.65810029],
       [ 5.        , -1.41721122,  0.65810029, -0.65810029],
       [ 5.        , -0.98532399, -1.37887681,  1.37887681],
       [ 5.        , -0.54968122,  0.65810029, -0.65810029]])

In [16]:
from sklearn.cluster import Birch

# define the model
model = Birch(threshold=0.01, n_clusters=4)
# fit the model
model.fit(x)
# assign a cluster to each example
yhat = model.predict(x)
# retrieve unique clusters
clusters = unique(yhat)
print(clusters)

[0 1 2 3]

In [8]:
new_df = dataset.iloc[:, [2, 7, 10, 11]].copy()
new_df['clusters'] = yhat
new_df.head()
display(new_df)

,child_age,mean_reaction_time,percentage_no_of_correct_responses,oer,clusters
79,4,1448,100.000000,0.000000,2
80,4,1331,100.000000,0.000000,2
81,4,1426,100.000000,0.000000,2
82,4,1632,100.000000,0.000000,1
83,4,1340,90.000000,10.000000,3
84,4,1564,100.000000,0.000000,1
85,4,1366,80.000000,20.000000,0
86,4,1291,100.000000,0.000000,2
87,4,2032,80.000000,20.000000,0
88,4,1789,90.000000,10.000000,0
89,4,1680,100.000000,0.000000,1
90,4,1317,90.000000,10.000000,3
91,4,1040,100.000000,0.000000,2
92,4,1142,100.000000,0.000000,2
93,4,1168,100.000000,0.000000,2
94,4,1150,100.000000,0.000000,2
95,4,1270,100.000000,0.000000,2
96,4,1457,90.000000,10.000000,3
97,4,1180,100.000000,0.000000,2
98,4,1261,90.000000,10.000000,3
99,4,1234,70.000000,30.000000,0
100,4,1165,100.000000,0.000000,2
101,4,1238,100.000000,0.000000,2
102,4,1830,90.000000,10.000000,0
103,4,1657,80.000000,20.000000,0
104,4,1817,70.000000,30.000000,0
105,5,1600,91.666667,8.333333,3
106,5,1396,91.666667,8.333333,3
107,5,1380,100.000000,0.000000,2
108,5,1350,100.000000,0.000000,2
109,5,1310,100.000000,0.000000,2
110,5,1462,100.000000,0.000000,2
111,5,1069,100.000000,0.000000,2
112,5,1221,100.000000,0.000000,2
113,5,1775,83.333333,16.666667,0
114,5,1852,83.333333,16.666667,0
115,5,1598,91.666667,8.333333,3
116,5,1785,100.000000,0.000000,1
117,5,1628,100.000000,0.000000,1
118,5,1758,100.000000,0.000000,1
119,5,1215,100.000000,0.000000,2
120,5,1134,100.000000,0.000000,2
121,5,1364,91.666667,8.333333,3
122,5,1499,100.000000,0.000000,2
123,5,1998,100.000000,0.000000,1
124,5,1916,83.333333,16.666667,0
125,5,1152,100.000000,0.000000,2
126,5,1086,100.000000,0.000000,2
127,5,1207,100.000000,0.000000,2
128,5,1047,100.000000,0.000000,2
129,5,1162,83.333333,16.666667,0
130,5,1278,100.000000,0.000000,2

In [9]:
from sklearn.metrics import silhouette_score,calinski_harabasz_score,davies_bouldin_score

print("Silhouette Coefficient: %0.3f" % silhouette_score(x, yhat))
print("Calinski-Harabasz Index: %0.3f" % calinski_harabasz_score(x, yhat))
print("Davies-Bouldin Index: %0.3f" % davies_bouldin_score(x, yhat))

Silhouette Coefficient: 0.401
Calinski-Harabasz Index: 41.707
Davies-Bouldin Index: 0.932

# Cluster Analysis

## Cluster 1

In [10]:
len(new_df[new_df["clusters"] == 0])

11

In [11]:
cluster_0 = new_df[new_df["clusters"] == 0 ]
display(cluster_0)

,child_age,mean_reaction_time,percentage_no_of_correct_responses,oer,clusters
85,4,1366,80.000000,20.000000,0
87,4,2032,80.000000,20.000000,0
88,4,1789,90.000000,10.000000,0
99,4,1234,70.000000,30.000000,0
102,4,1830,90.000000,10.000000,0
103,4,1657,80.000000,20.000000,0
104,4,1817,70.000000,30.000000,0
113,5,1775,83.333333,16.666667,0
114,5,1852,83.333333,16.666667,0
124,5,1916,83.333333,16.666667,0
129,5,1162,83.333333,16.666667,0

In [12]:
cluster_0 = new_df[new_df["clusters"] == 0 ]

maxVal = cluster_0['mean_reaction_time'].max()
minVal = cluster_0['mean_reaction_time'].min()

print("mean_reaction_time min - ", minVal)
print("mean_reaction_time max - ", maxVal)
print()

maxVal = cluster_0['percentage_no_of_correct_responses'].max()
minVal = cluster_0['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_0['oer'].max()
minVal = cluster_0['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)

mean_reaction_time min -  1162
mean_reaction_time max -  2032

percentage_no_of_correct_responses min -  70.0
percentage_no_of_correct_responses max -  90.0

oer min -  10.0
oer max -  30.0

## Cluster 2

In [13]:
len(new_df[new_df["clusters"] == 1])

7

In [14]:
cluster_1 = new_df[new_df["clusters"] == 1 ]
display(cluster_1)

,child_age,mean_reaction_time,percentage_no_of_correct_responses,oer,clusters
82,4,1632,100.0,0.0,1
84,4,1564,100.0,0.0,1
89,4,1680,100.0,0.0,1
116,5,1785,100.0,0.0,1
117,5,1628,100.0,0.0,1
118,5,1758,100.0,0.0,1
123,5,1998,100.0,0.0,1

In [15]:
cluster_1 = new_df[new_df["clusters"] == 1 ]

maxVal = cluster_1['mean_reaction_time'].max()
minVal = cluster_1['mean_reaction_time'].min()

print("mean_reaction_time min - ", minVal)
print("mean_reaction_time max - ", maxVal)
print()

maxVal = cluster_1['percentage_no_of_correct_responses'].max()
minVal = cluster_1['percentage_no_of_correct_responses'].min()

print("percentage_no_of_correct_responses min - ", minVal)
print("percentage_no_of_correct_responses max - ", maxVal)
print()

maxVal = cluster_1['oer'].max()
minVal = cluster_1['oer'].min()

print("oer min - ", minVal)
print("oer max - ", maxVal)

mean_reaction_time min -  1564
mean_reaction_time max -  1998

percentage_no_of_correct_responses min -  100.0
percentage_no_of_correct_responses max -  100.0

oer min -  0.0
oer max -  0.0